/*==================================================================*\
  VulkanTools.cpp
  ------------------------------------------------------------------
  Purpose:
  

  ------------------------------------------------------------------
  ©2010-2018 Eldritch Entertainment, LLC.
\*==================================================================*/

//==================================================================//
// INCLUDES
//==================================================================//
#include <Graphics/Vulkan/VulkanTools.hpp>
//------------------------------------------------------------------//

namespace Eldritch2 { namespace Graphics { namespace Vulkan {

	const struct FormatDescriptor TextureFormats[size_t( GpuFormat::MAX ) + 1] = {
		// R8G8B8A8_Unorm
		{ VK_FORMAT_R8G8B8A8_UNORM, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// R8G8B8A8_Srgb
		{ VK_FORMAT_R8G8B8A8_SRGB,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// R8G8B8A8_Snorm
		{ VK_FORMAT_R8G8B8A8_SNORM, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// R8G8B8A8_Uint
		{ VK_FORMAT_R8G8B8A8_UINT,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// BC1_Unorm
		{ VK_FORMAT_BC1_RGB_UNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_ONE} },
		// BC1_Srgb
		{ VK_FORMAT_BC1_RGB_SRGB_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_ONE} },
		// BC3_Unorm
		{ VK_FORMAT_BC3_UNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// BC3_Srgb
		{ VK_FORMAT_BC3_SRGB_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// BC3_YCoCg (CoCg_Y in bit layout, swizzled)
		{ VK_FORMAT_BC3_UNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_A, VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ONE} },
		// BC5_Unorm
		{ VK_FORMAT_BC5_UNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ZERO, VK_COMPONENT_SWIZZLE_ONE} },
		// BC5_Snorm
		{ VK_FORMAT_BC5_SNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ZERO, VK_COMPONENT_SWIZZLE_ONE} },
		// BC6_Float
		{ VK_FORMAT_BC6H_SFLOAT_BLOCK, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ZERO, VK_COMPONENT_SWIZZLE_ONE} },
		// BC7_Unorm
		{ VK_FORMAT_BC7_UNORM_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ZERO, VK_COMPONENT_SWIZZLE_ONE} },
		// BC7_Srgb
		{ VK_FORMAT_BC7_SRGB_BLOCK,  {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_ZERO, VK_COMPONENT_SWIZZLE_ONE} },
		// R16G16B16A16_Float
		{ VK_FORMAT_R16G16B16A16_SFLOAT, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// R32G32B32A32_Float
		{ VK_FORMAT_R32G32B32A32_SFLOAT, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// D32_Float
		{ VK_FORMAT_D32_SFLOAT, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// D32S8_Float
		{ VK_FORMAT_D32_SFLOAT_S8_UINT, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// D16_Float
		{ VK_FORMAT_D16_UNORM, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
		// D16S8_Float
		{ VK_FORMAT_D16_UNORM_S8_UINT, {VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A} },
	};

}}} // namespace Eldritch2::Graphics::Vulkan
