//
// src\Animation\AnimateSkeleton_generated_avx.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_SRC_ANIMATION_ANIMATESKELETON_GENERATED_AVX_H
#define ISPC_SRC_ANIMATION_ANIMATESKELETON_GENERATED_AVX_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void BulkHermite(float * values, const uint32_t * channels, const float * startTimes, const float * reciprocalDurations, const uint16_t * startValues, const uint16_t * endValues, const uint16_t * startTangents, const uint16_t * endTangents, uint32_t trackCount, float time);
    extern void BulkHermiteWithDerivative(float * values, float * derivatives, const uint32_t * channels, const float * startTimes, const float * reciprocalDurations, const uint16_t * startValues, const uint16_t * endValues, const uint16_t * startTangents, const uint16_t * endTangents, uint32_t trackCount, float time);
    extern void CopyPalette(float * values, const float * sourceValues, uint32_t valueCount);
    extern void LinearBlend(float * finalValues, const float * sourceValues, float sourceFactor, const float * targetValues, float targetFactor, uint32_t valueCount);
    extern void TransposeTransforms(float transforms[][4], const float * sourceValues, uint32_t transformCount);
    extern void lol();
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_SRC_ANIMATION_ANIMATESKELETON_GENERATED_AVX_H
