//
// src\Animation\AnimateSkeletons_generated.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_SRC_ANIMATION_ANIMATESKELETONS_GENERATED_H
#define ISPC_SRC_ANIMATION_ANIMATESKELETONS_GENERATED_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Vector types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_VECTOR_int16_t4__
#define __ISPC_VECTOR_int16_t4__
#ifdef _MSC_VER
__declspec( align(32) ) struct int16_t4 { int16_t v[4]; };
#else
struct int16_t4 { int16_t v[4]; } __attribute__ ((aligned(32)));
#endif
#endif

#ifndef __ISPC_VECTOR_int8_t4__
#define __ISPC_VECTOR_int8_t4__
#ifdef _MSC_VER
__declspec( align(32) ) struct int8_t4 { int8_t v[4]; };
#else
struct int8_t4 { int8_t v[4]; } __attribute__ ((aligned(32)));
#endif
#endif



#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif

#ifndef __ISPC_STRUCT_GpuTransform__
#define __ISPC_STRUCT_GpuTransform__
struct GpuTransform {
    int16_t4  translation;
    int16_t4  orientation;
};
#endif

#ifndef __ISPC_STRUCT_AnimationKey__
#define __ISPC_STRUCT_AnimationKey__
struct AnimationKey {
    int16_t4  translation;
    int8_t4  orientation;
    uint16_t targetBone;
};
#endif

#ifndef __ISPC_STRUCT_GpuTransformWithVelocity__
#define __ISPC_STRUCT_GpuTransformWithVelocity__
struct GpuTransformWithVelocity {
    int16_t4  translation;
    int16_t4  linearVelocity;
    int16_t4  orientation;
    int16_t4  angularVelocity;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void AnimateSkeleton(struct GpuTransform * out, const struct AnimationKey * const  * tracks, uint32_t trackCount);
    extern void AnimateSkeletonWithVelocity(struct GpuTransformWithVelocity * out, const struct AnimationKey * const  * tracks, uint32_t trackCount);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_SRC_ANIMATION_ANIMATESKELETONS_GENERATED_H
